sequential:
	g++ sequentialConvolution.cpp -I./libraries/include -L./libraries/lib/ -lpng -o sequentialConvolution
run_sequentialconvolution:
	LD_LIBRARY_PATH=./libraries/lib ./sequentialConvolution google.png google_m.png
